version: '3'

services:
  wbeep:
    image: dblodgett-usgs/hydrogeoenv-custom:latest
    container_name: hydrogeoenv
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/jupyter
    command: >
      sh -c "usermod -a -G docker jovyan &&
             start.sh jupyter lab --LabApp.token='' --ContentsManager.root_dir='/jupyter' --NotebookApp.notebook_dir='/jupyter' --NotebookApp.contents_manager_class='ipymd.IPymdContentsManager' --NotebookApp.contents_manager_class='jupytext.TextFileContentsManager'"
             